server:
  port: 9099

spring:
  application:
    name: book-management-service
  datasource:
    url: jdbc:h2:mem:book_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 15
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      data-locations: classpath:db/data.sql

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        sql: DEBUG

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs