server:
  port: 9099

spring:
  application:
    name: book-management-service
  datasource:
    url: jdbc:h2:mem:book_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
